/* lib/projects.ts → as window.PROJECTS for the prototype.
   Shape mirrors the production interface so a CMS swap is trivial. */

const PROJECTS = [
  {
    slug: "aimtec-tal",
    title: "Aimtec TAL",
    client: "Aimtec",
    year: "2025",
    services: ["Web Design", "Web Development", "Branding"],
    cover: { hue: 210, label: "platform identity / aimtec" },
    gallery3: [{ hue: 210, label: "dashboard" }, { hue: 50, label: "mobile" }, { hue: 220, label: "in-situ" }],
    hasDetail: true,
    brief: "Redesign produktové platformy pro logistiku skladu — od strategie přes vizuální systém až po implementaci. Cílem bylo udělat z technicky náročného produktu nástroj, který si lidé chtějí pustit ráno před kávou.",
    role: "Strategie · Identita · Web · Vývoj",
    gallery: [
      { kind: "full", hue: 210, label: "hero / dashboard zoom" },
      { kind: "pair", hueA: 210, hueB: 50, labelA: "logo lockup", labelB: "barevný systém" },
      { kind: "offset", hue: 35, label: "typografická škála" },
      { kind: "full", hue: 220, label: "in-situ / mobil" },
    ],
    sections: [
      { heading: "Přístup", body: "Začali jsme tím, že jsme tým posadili do skladu. Ne na meeting — opravdu do skladu. Bez té zkušenosti by produkt zůstal abstraktní. Po čtyřech dnech jsme měli mapu třiceti klíčových interakcí a věděli jsme, kde produkt drhne nejvíc." },
      { heading: "Řešení", body: "Postavili jsme designový systém okolo tří denních režimů — ranní příjem, denní vychystávání a večerní inventura. Každý režim má vlastní rytmus, kontrast i hierarchii. Stejné komponenty, jiné nasazení." },
    ],
    video: null,
  },
  {
    slug: "siment",
    title: "Siment",
    client: "Siment Group",
    year: "2026",
    services: ["Strategie", "Komunikace", "Identita"],
    cover: { hue: 30, label: "rebrand / siment" },
    gallery3: [{ hue: 30, label: "key visual" }, { hue: 200, label: "outdoor" }, { hue: 30, label: "personas" }],
    hasDetail: true,
    brief: "Komplexní rebranding rodinné firmy v oboru reality a finance. Z konzervativního hráče jsme udělali partnera, kterému lidé volají dřív, než zavolají bance.",
    role: "Strategie · Identita · Brand voice",
    gallery: [
      { kind: "full", hue: 30, label: "key visual" },
      { kind: "pair", hueA: 30, hueB: 200, labelA: "tisk / brožura", labelB: "outdoor" },
      { kind: "offset", hue: 30, label: "personas" },
    ],
    sections: [
      { heading: "Přístup", body: "Strategická fáze trvala dvanáct týdnů. Mluvili jsme s šestadvaceti klienty, sedmi makléři a třemi konkurenty. Z toho vznikl claim, který drží i bez loga." },
      { heading: "Řešení", body: "Identita stojí na třech personách — Sekretářka Lucie, Ředitelka Františka, Architektka Amálie. Každá má vlastní tonalitu, formát i kanál. Komunikace se tak nikdy netváří jako jeden hlas pro všechny." },
    ],
    video: null,
  },
  {
    slug: "so-concrete",
    title: "So Concrete",
    client: "So Concrete",
    year: "2024",
    services: ["Web Design", "Web Development"],
    cover: { hue: 0, label: "site / so concrete" },
    gallery3: [{ hue: 0, label: "tisk" }, { hue: 0, label: "panel" }, { hue: 0, label: "studio" }],
    hasDetail: true,
    brief: "Web pro studio, které tiskne na 3D tiskárně z betonu. Materiál je extrémně specifický — web musel mít stejnou váhu, hrubost a klid jako jeho výstupy.",
    role: "Web · Vývoj · Art direction",
    gallery: [
      { kind: "full", hue: 0, label: "hero / proces tisku" },
      { kind: "offset", hue: 0, label: "detail výtisku" },
      { kind: "pair", hueA: 0, hueB: 0, labelA: "výstavní instalace", labelB: "fasádní panel" },
      { kind: "full", hue: 0, label: "studio shot" },
    ],
    sections: [
      { heading: "Přístup", body: "Beton se nedá fotit hezky. Musí se fotit pravdivě. Strávili jsme tři dny ve výrobní hale a místo plánovaných deseti záběrů přivezli devadesát čtyři." },
      { heading: "Řešení", body: "Web je z 80 % fotografie a z 20 % typografie. Nic víc, nic míň. Žádné ikony, žádné shadow boxy, žádné zaoblené rohy. Jako materiál sám." },
    ],
    video: { embed: "//www.youtube.com/embed/dQw4w9WgXcQ", aspect: "16/9" },
  },
  {
    slug: "jetmasters",
    title: "JetMasters",
    client: "JetMasters",
    year: "2025",
    services: ["Web Design"],
    cover: { hue: 220, label: "site / jetmasters" },
    gallery3: [{ hue: 220, label: "hero" }, { hue: 220, label: "rezervace" }, { hue: 220, label: "portál" }],
    hasDetail: true,
    brief: "Servisní web pro provozovatele soukromých letadel. Krátký funnel, dva CTA, žádný zbytek. Celé je to o tom, aby pilot stihl odbavení.",
    role: "Web · UX",
    gallery: [
      { kind: "full", hue: 220, label: "hero" },
      { kind: "pair", hueA: 220, hueB: 220, labelA: "rezervace", labelB: "stav letu" },
      { kind: "offset", hue: 220, label: "B2B portál" },
    ],
    sections: [
      { heading: "Přístup", body: "Pilot na poslední chvíli nemá náladu na hezké animace. Cílili jsme na to, aby se rezervace dala dokončit za 14 sekund od vstupu na web." },
      { heading: "Řešení", body: "Tři vstupní cesty: pravidelný klient, nový klient, nouzový režim. Každá má vlastní layout. Celý web je sub-300kb." },
    ],
    video: null,
  },
  {
    slug: "papirna-je",
    title: "Papírna Je",
    client: "Papírna Je",
    year: "2024",
    services: ["Web Design", "Web Development", "Branding"],
    cover: { hue: 35, label: "rebrand / papírna" },
    gallery3: [{ hue: 35, label: "interiér" }, { hue: 35, label: "plakát" }, { hue: 35, label: "noc" }],
    hasDetail: true,
    brief: "Stará papírna, která se mění na kulturní centrum. Naším úkolem bylo přenést tu krásnou hrubost cihel a strojů do digitálního světa, aniž bychom jí ublížili.",
    role: "Identita · Web · Print",
    gallery: [
      { kind: "full", hue: 35, label: "interiér" },
      { kind: "offset", hue: 35, label: "plakát" },
      { kind: "pair", hueA: 35, hueB: 35, labelA: "vstupenka", labelB: "wayfinding" },
      { kind: "full", hue: 35, label: "venku v noci" },
    ],
    sections: [
      { heading: "Přístup", body: "Místo má vlastní zvuk a vlastní teplotu. Identita to musela respektovat — žádné ikonky parníků a hracích karet, žádné nostalgické serify." },
      { heading: "Řešení", body: "Sazba je čistě monospace, fotografie zůstávají v původních barvách bez post-produkce. Jediný akcent je tepelně modrá z provozního značení." },
    ],
    video: null,
  },
  {
    slug: "bc-real",
    title: "BC Real",
    client: "BC Real",
    year: "2025",
    services: ["Web Design", "Web Development"],
    cover: { hue: 200, label: "site / bc real" },
    gallery3: [{ hue: 200, label: "listing" }, { hue: 200, label: "detail" }, { hue: 200, label: "mapa" }],
    hasDetail: true,
    brief: "Realitní portál, který ukazuje jen to, co reálně existuje. Žádné rendery, žádné stockové kuchyně. Jen byty, jak vypadají v úterý ve čtyři odpoledne.",
    role: "Web · Vývoj · Foto art-direction",
    gallery: [
      { kind: "full", hue: 200, label: "hero / listing" },
      { kind: "pair", hueA: 200, hueB: 200, labelA: "detail", labelB: "filtr" },
      { kind: "offset", hue: 200, label: "mapa" },
    ],
    sections: [
      { heading: "Přístup", body: "Většina realitních webů lže fotografií. My jsme se rozhodli foto-protokol držet pevně: jeden objektiv, jedno místo, jedno pravidlo o tom, kde stát při fotografování koupelny." },
      { heading: "Řešení", body: "Web je skoro až nudný — a o to právě jde. Důvěryhodnost je v opakování. Klient vrátí návštěvníka třikrát zpátky, než pošle dotaz." },
    ],
    video: null,
  },
  // Without detail (no /projekty/[slug]) — but visually equal in grid
  { slug: "vinarstvi-brem", title: "Vinařství Brém", client: "Vinařství Brém", year: "2023", services: ["Branding", "Print"], cover: { hue: 350, label: "vinařství brém" }, hasDetail: false },
  { slug: "okpoint-plzen", title: "OK Point Plzeň", client: "OK Point", year: "2024", services: ["Web Design", "Web Development"], cover: { hue: 25, label: "ok point" }, hasDetail: false },
  { slug: "stavby-lego", title: "Stavby Lego", client: "Lego Stavby", year: "2024", services: ["Identita"], cover: { hue: 220, label: "stavby" }, hasDetail: false },
  { slug: "kavarna-vlna", title: "Kavárna Vlna", client: "Vlna", year: "2023", services: ["Branding", "Print"], cover: { hue: 40, label: "kavárna" }, hasDetail: false },
  { slug: "festival-ozveny", title: "Festival Ozvěny", client: "Ozvěny", year: "2024", services: ["Identita", "Print"], cover: { hue: 280, label: "festival" }, hasDetail: false },
  { slug: "klinika-rekona", title: "Klinika Rekona", client: "Rekona", year: "2025", services: ["Web Design"], cover: { hue: 180, label: "klinika" }, hasDetail: false },
  { slug: "studio-arbor", title: "Studio Arbor", client: "Arbor", year: "2023", services: ["Identita"], cover: { hue: 130, label: "studio" }, hasDetail: false },
  { slug: "hudebniny-kos", title: "Hudebniny Koš", client: "Koš", year: "2024", services: ["Web Design"], cover: { hue: 15, label: "hudebniny" }, hasDetail: false },
  { slug: "treti-pol", title: "Třetí Pól", client: "Třetí Pól z.s.", year: "2025", services: ["Branding", "Web Design"], cover: { hue: 195, label: "neziskovka" }, hasDetail: false },
];

window.PROJECTS = PROJECTS;
